DATA_DIRECTORY = 'data/movies'
JPG_SUFFIX = '.jpg'
XML_SUFFIX = '.xml'
DOT_TOKEN = '.'
UNDERSCORE_TOKEN = '_'
FILE_LOCATION_COLUMN = 'file_location'
WIDTH_COLUMN = 'width'
HEIGHT_COLUMN = 'height'
DEPTH_COLUMN = 'depth'
XMIN_COLUMN = 'xmin'
YMIN_COLUMN = 'ymin'
XMAX_COLUMN = 'xmax'
YMAX_COLUMN = 'ymax'
OBJECT_COLUMN = 'object'

PARSED_DATAFRAME_COLUMNS = [FILE_LOCATION_COLUMN, WIDTH_COLUMN, HEIGHT_COLUMN,
                            DEPTH_COLUMN, XMIN_COLUMN, YMIN_COLUMN,
                            XMAX_COLUMN, YMAX_COLUMN, OBJECT_COLUMN]

NUMERIC_COLUMNS = [WIDTH_COLUMN, HEIGHT_COLUMN, DEPTH_COLUMN, XMIN_COLUMN,
                   YMIN_COLUMN, XMAX_COLUMN, YMAX_COLUMN]

ANNOTATIONS_COLUMNS_RETINA_FORMAT = [FILE_LOCATION_COLUMN, XMIN_COLUMN,
                                     YMIN_COLUMN, XMAX_COLUMN, YMAX_COLUMN,
                                     OBJECT_COLUMN]
